
name: Ruby

on:
  push:
    branches: [ master ]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: 2.6
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - name: Install nanoc
      run: gem install nanoc -v 3.8.0
      
    - name: Install other dependencies
      run: gem install bluecloth

    - name: Build website
      run: nanoc

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: output
